### ISSUE TITLE
Enhancement: `extern module` — instantiate and co-simulate a legacy SystemVerilog leaf inside an ARCH design (prototype runs today)

### ISSUE THREAD

**Issue by nogate-ai** [arch-hdl-lang/arch-com#981]
## Summary

Add a first-class **external SystemVerilog leaf** to ARCH — an interface-only construct that names a `.v`/`.sv` file — and teach `arch sim` to co-simulate it by Verilating that file and linking it in behind a generated adapter:

```arch
extern module LegacyCrc
  port clk: in Clock<SysDomain>;
  port rst: in Reset<Sync>;
  port din: in UInt<8>;
  port dout: out UInt<8>;
  sv_source "rtl/legacy_crc.v";
end extern module LegacyCrc
```

`arch build` passes the file through to the SV file list (the instantiation already works — see below). `arch sim` Verilates it and links the real RTL into the native C++ sim.

**I built a working prototype of the sim half by hand — it runs and produces bit-correct results today** (§3). The compiler work is to generate the ~15-line adapter and the build plumbing that I wrote manually.

## 1. Problem: ARCH is all-or-nothing at the design boundary

You cannot instantiate a legacy SV block inside an ARCH design and simulate it. That has two costs.

**(a) Adoption.** Nobody rewrites an SoC. Incremental adoption — port one block, keep the rest — is the only realistic path, and it is exactly what ARCH cannot do today. Our own RealBench work is the proof: `tests/e203/` is **62 `.arch` files / 10,649 lines** that had to be ported *before any of it could be simulated in context*.

**(b) It removes the only cheap oracle for the dominant live bug class.** Every functional bug in the backlog — #877 (SRAI decodes as SRLI), #879 (IFU fetch path deadlocks, "no instruction can reach decode in ifu_top/core_top/soc_top"), #880 (dec_info layout disagreement), #881, #869 — is an ARCH-port-vs-reference-RTL divergence found by reading `.v` by eye.

With mixed-language instantiation, #879 becomes a **bisection**: build `core_top` with all-ARCH leaves (fails), swap leaves back to the reference `.v` one at a time, and the broken leaf falls out in log(N) sims. That is a fundamentally cheaper loop than the hand-written-testbench-per-module process #799 has 45 more modules queued for.

This is **complementary to, not overlapping with, #883 (`arch xcheck`)**. #883 diffs *one whole ARCH module* against *one reference module*, side by side. This issue instantiates reference RTL *inside* an ARCH hierarchy. #883 cannot localize #879, because the divergence is in the composition of leaves that each pass in isolation.

| layer | property | mechanism |
|---|---|---|
| native sim ≡ arch-emitted SV | compiler correctness | `arch equiv` (#752) |
| arch module ≡ reference module | port correctness, flat | `arch xcheck` (#883) |
| arch hierarchy **containing** reference leaves | port correctness, **hierarchical / bisectable** | **this issue** |

## 2. Current state, measured on `origin/main` @ 173027a3

A hand-written `.archi` naming a nonexistent module is already accepted as an opaque blackbox — §30.2 discovery finds it, and §26's comb-loop analysis already documents the over-approximation for interface-only stubs ("every output depends on every input except registered outputs"). So the build path works, undocumented and by accident:

```
$ cat LegacyCrc.archi          # hand-written; no .arch source anywhere
module LegacyCrc
  port clk: in Clock<SysDomain>;  port rst: in Reset<Sync>;
  port din: in UInt<8>;           port dout: out UInt<8>;
end module LegacyCrc

$ arch check Wrapper.arch
OK: no errors
$ arch build Wrapper.arch --o Wrapper.sv     # emits a correct blackbox instantiation
  LegacyCrc u_crc ( .clk(clk), .rst(rst), .din(a), .dout(crc_out) );
```

The three gaps:

**(i) `arch sim` fails with a raw C++ error, not an ARCH diagnostic** (exit 1):
```
arch_sim_build/VWrapper.h:5:10: fatal error: 'VLegacyCrc.h' file not found
```
Whatever else is decided here, a bodyless module reaching sim codegen should produce an ARCH-level diagnostic naming the module and the `.archi`.

**(ii) `arch formal` treats the stub as a second top:**
```
× multiple modules in input (LegacyCrc, Wrapper); specify --top <Name>
```

**(iii) Nothing checks the `.archi` against the real SV.** Port name, width, direction and count mismatches are silent in `arch check` and only surface at SV elaboration — or never, in sim.

## 3. Prototype: it already works, with ~15 lines of glue

`arch sim --help` states it "Generates Verilator-compatible C++ models", and it delivers more than that phrase implies. For the blackbox above, sim codegen emits:

```cpp
VLegacyCrc _inst_u_crc;        // class name == Verilator's for module LegacyCrc
_inst_u_crc.clk = clk;  _inst_u_crc.din = a;  _inst_u_crc.eval_comb();
```

and Verilator, given the same module, emits public members `clk`, `rst`, `din`, `dout` — **the port ABI already matches, name for name**, because both derive from the same port list.

Two real deltas remain:
- **eval API**: ARCH drives sub-instances split-phase (`eval_comb()` / `eval_posedge()`); Verilator exposes one `eval()`.
- **header collision**: `arch sim` ships its *own* minimal `arch_sim_build/verilated.h` stub with non-Verilator APIs (`Verilated::traceFile()`, `Verilated::claimTrace()`). It shadows the real runtime header, so the two sides cannot share one translation unit.

Both are solved by a **pimpl adapter** — no Verilator headers in the ARCH-facing header:

```cpp
// vshim/VLegacyCrc.h — generated, no Verilator includes
class VLegacyCrc {
public:
  uint8_t clk = 0, rst = 0, din = 0, dout = 0;   // mirrors the .archi ports
  VLegacyCrc(); ~VLegacyCrc();
  void eval_comb();
  void eval_posedge();
private:
  void* _impl;
};
```
```cpp
// vshim/VLegacyCrc_impl.cpp — generated, compiled against the REAL verilated.h
void VLegacyCrc::eval_comb() {
  auto* m = M(_impl); m->rst = rst; m->din = din; m->eval(); dout = m->dout;
}
void VLegacyCrc::eval_posedge() {
  auto* m = M(_impl); m->rst = rst; m->din = din;
  m->clk = 0; m->eval(); m->clk = 1; m->eval(); dout = m->dout;
}
```

Built as two object sets (ARCH side with the stub header, Verilator side with the real one) and linked against `libVLegacyCrcRef.a` + `libverilated.a`, plus a one-line `double sc_time_stamp() { return 0; }`:

```
=== RUN (ARCH module + Verilated SV leaf) ===
cycle 0: a=0x81 y=0x59
cycle 1: a=0x82 y=0x5f
cycle 2: a=0x83 y=0x5d
```

Bit-exact against the SV leaf's `dout <= {din[6:0], din[7]} ^ 8'h5a` (`0x81` → `0x03 ^ 0x5a` = `0x59`, etc.). Verilator 5.048, clang++, macOS arm64.

## 4. Implementation sketch

1. **Grammar** (`src/lexer.rs`/`parser.rs`/`ast.rs`): `extern module` + `sv_source "path";`. Interface-only body — ports, params, `sv_source`, nothing else. Reuses the `.archi` shape; a `.archi` may also carry `sv_source`. *Grammar-surface change: needs maintainer sign-off and a `doc/` update in the same PR.*
2. **Typecheck**: an `extern module` may only be `inst`-ed; reject `arch build`/`sim`/`formal` with it as top. Fix (ii) — exclude extern modules from top-module inference.
3. **`arch build`**: unchanged instantiation (already correct); additionally emit the `sv_source` paths into the file list / a `.f` manifest so downstream tools pick them up.
4. **`arch sim`**: for each reachable extern leaf, run `verilator --cc --build <sv_source> --prefix V<Name>Ref`, generate the adapter pair above into the build dir, and extend the compile/link line (two include sets, the `.a`s, `sc_time_stamp`). Fix (i) as the fallback when there is no `sv_source`.
5. **Conformance check** (fixes (iii)): after Verilating, diff the model's port set against the declared ports and error on name/width/direction mismatch. This is the check that makes the feature safe — it is cheap because Verilator has already parsed the SV.
6. **`arch formal`**: keep extern leaves uninterpreted (the §26 over-approximation already has the right shape), or refuse with a clear message in v1.

## 5. Open design questions

- **Async reset / multi-clock leaves.** The prototype drives one posedge per parent `eval_posedge()`. A leaf with its own clock domain, a negedge-triggered flop, or async reset needs a richer adapter contract. Suggest v1 restricts extern leaves to a single `Clock<D>` port matching the parent's domain, and errors otherwise.
- **Comb settle.** ARCH's `eval_comb()` runs a fixed 3-pass settle loop (cf. #899). A combinational extern leaf gets `eval()` called 3× — idempotent and fine — but a leaf on a backward chain inherits #899's shallow-settle limitation.
- **Verilator as a hard `arch sim` dependency.** Today it is only a verification dependency. Making it required *when an extern leaf is present* seems acceptable; the error when it is missing must say so plainly.
- **X-propagation.** The Verilated leaf is 2-state under default flags, matching arch sim. Worth stating in doc rather than silently assuming.

## 6. Why this is worth doing now

The prototype says the hard parts are already built — the port ABI matches by construction and the build path already emits correct blackbox instantiations. What is missing is a grammar marker, a generated 15-line adapter, and build plumbing. In exchange it turns the highest-cost bug class in the repo (#879/#880/#881, plus the 45 modules queued behind #799) from *read the reference `.v` by eye* into *bisect by leaf substitution*, and it unblocks the incremental-adoption story that ARCH currently has no answer for.

---
*Filed by the daily-research sweep. Prototype artifacts reproducible from the steps in §3; measured against `origin/main` @ 173027a3, Verilator 5.048.*
